[build-system]
requires = ["setuptools>=68","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unv"
version = "0.4.1"
requires-python = ">=3.9"
dependencies = ["pygments", "lief","pefile","fastapi","uvicorn","python-multipart"]
authors = [{name="Jerrod Baker"}]
readme = "README.md"


[tool.setuptools.packages.find]
where = ["."]
include = ["unv*"]

[project.scripts]
unv = "unv.cli:main"
unveil = "unv.cli:main"

[tool.setuptools]
license-files = []
