[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unv"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["lief","pefile","fastapi","uvicorn","python-multipart",
    "pygments"]

authors = [{ name = "Jerrod Baker" }]
readme = "README.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["unv*", "unveil*"]

[tool.setuptools.package-data]
unv = ["Unveil_banner.txt"]

[tool.setuptools]
license-files = []

[project.scripts]
unv = "unv.cli:main"
unveil = "unveil.cli:main"
unv-daemon = "unv.daemon:main"
